str = "Hello"
print(str[3])
print(str[-2])
print(str[:5])
print(str[:-2])
print(str[::2])
print(str[1::2])
print(str[::-1])
print(str[::-2])
print(len(str))
str2 = "TEST-STR"
print(str2[3])
print(str2[-2])
print(str2[:5])
print(str2[:-2])
print(str2[::2])
print(str2[1::2])
print(str2[::-1])
print(str2[::-2])
print(len(str2))
